Repository boostcamp-2020/Project03-A-TOTP, pull requests merged in 2020-11, with the labels that each got.

#2 [iOS] 폴더 생성
  iOS/README.md
Labels: iOS

#4 [BE] Sequelize ORM
  WEB/BE/.env.template
  WEB/BE/app.js
  WEB/BE/config/config.js
  WEB/BE/models/WEB/AUTHS.js
  WEB/BE/models/WEB/LOGS.js
  WEB/BE/models/WEB/USERS.js
  WEB/BE/models/iOS/DEVICES.js
  WEB/BE/models/iOS/TOKENS.js
  WEB/BE/models/iOS/USERS.js
  WEB/BE/models/sequelizeIOS.js
  WEB/BE/models/sequelizeWEB.js
  WEB/BE/seeders/dummyDataWEB.js
Labels: BE

#54 [FE] 라우팅 설정
  WEB/FE/.eslintrc.json
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/route/PrivateRoute.tsx
Labels: FE

#57 [iOS] 프로젝트 생성 후 SwiftLint 추가
  .gitignore
  README.md
  WEB/BE/.env.template
  WEB/BE/.eslintrc
  WEB/BE/.prettierrc
  WEB/BE/app.js
  WEB/BE/package-lock.json
  WEB/BE/package.json
  WEB/FE/.eslintignore
  WEB/FE/.eslintrc.json
  WEB/FE/.prettierrc.json
  WEB/FE/babel.config.js
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/App.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/static/index.html
  WEB/FE/tsconfig.json
  WEB/FE/webpack.common.js
  WEB/FE/webpack.dev.js
  WEB/FE/webpack.prod.js
  WEB/README.md
  deploy_rsa.enc
  iOS/DaDaIkSeon/.swiftlint.yml
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.xcworkspace/xcuserdata/eozinee.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/xcuserdata/eozinee.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/DaDaIkSeon/DaDaIkSeon.xcworkspace/contents.xcworkspacedata
  iOS/DaDaIkSeon/DaDaIkSeon.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/DaDaIkSeon/DaDaIkSeon/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Assets.xcassets/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/ContentView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Info.plist
  iOS/DaDaIkSeon/DaDaIkSeon/Preview Content/Preview Assets.xcassets/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeonTests/DaDaIkSeonTests.swift
  iOS/DaDaIkSeon/DaDaIkSeonTests/Info.plist
  iOS/DaDaIkSeon/DaDaIkSeonUITests/DaDaIkSeonUITests.swift
  iOS/DaDaIkSeon/DaDaIkSeonUITests/Info.plist
  iOS/DaDaIkSeon/Podfile
  iOS/DaDaIkSeon/Podfile.lock
Labels: iOS

#58 [iOS] TravisCI yml파일 수정, Cocoapods 버전 수정
  .travis.yml
  iOS/DaDaIkSeon/Podfile.lock
Labels: iOS

#56 [BE] eslint, prettier 수정
  WEB/BE/.eslintrc
  WEB/BE/.prettierrc
  WEB/BE/package-lock.json
  WEB/BE/package.json
Labels: BE

#60 [iOS] 메인 뷰 레이아웃 설정
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/be-pr.md
  .github/PULL_REQUEST_TEMPLATE/ios-pr.md
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Info.plist
  iOS/DaDaIkSeon/DaDaIkSeon/ContentView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
Labels: iOS

#61 [iOS] TOTP Token 모델 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Model/TOTPToken.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
Labels: iOS

#63 [iOS] TokenViewModel, TokenListViewModel 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Model/TOTPToken.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Model/Token.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenListView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenListViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenViewModel.swift
Labels: iOS

#64 [BE] 회원가입 API 구현 ( 비밀키생성 및 큐알코드 생성)
  WEB/BE/.env.template
  WEB/BE/.eslintrc
  WEB/BE/app.js
  WEB/BE/controllers/auth/index.js
  WEB/BE/controllers/user/index.js
  WEB/BE/models/WEB/AUTHS.js
  WEB/BE/models/WEB/LOGS.js
  WEB/BE/models/WEB/USERS.js
  WEB/BE/models/iOS/DEVICES.js
  WEB/BE/models/iOS/TOKENS.js
  WEB/BE/models/iOS/USERS.js
  WEB/BE/models/sequelizeIOS.js
  WEB/BE/models/sequelizeWEB.js
  WEB/BE/package-lock.json
  WEB/BE/package.json
  WEB/BE/routes/auth/index.js
  WEB/BE/routes/user/index.js
  WEB/BE/services/auth/index.js
  WEB/BE/services/user/index.js
  WEB/BE/utils/bcrypt/index.js
  WEB/BE/utils/crypto/index.js
Labels: BE

#67 [FE] GlobalStyle 적용
  WEB/FE/.eslintrc.json
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/style/globalStyle.ts
  WEB/FE/src/style/variable.ts
  WEB/FE/tsconfig.json
Labels: FE

#65 [BE] csrf 방어
  .travis.yml
  WEB/BE/.eslintrc.json
  WEB/BE/.prettierrc.json
  WEB/BE/middlewares/csrf.js
  WEB/BE/package-lock.json
  WEB/BE/package.json
  WEB/FE/package-lock.json
  WEB/FE/package.json
Labels: BE

#66 [BE] app.js 정리
  WEB/BE/.env.template
  WEB/BE/app.js
Labels: BE

#68 [FE] recaptcha v3 추가
  WEB/BE/.env.template
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/components/App.tsx
  WEB/FE/src/types/missingTypes.d.ts
  WEB/FE/tsconfig.json
Labels: FE

#70 [iOS] Main Cell View 로직 구현
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainCellViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenListViewModel.swift
Labels: iOS

#72 [iOS] Color Extension추가, SearchBar UI 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/Shadow.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/blue1.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/blue2.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/brown1.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/brown2.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/mint1.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/mint2.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/navy1.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/navy2.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/pink1.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/pink2.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/salmon1.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/salmon2.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Extensions/Color+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenListView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenListViewModel.swift
Labels: iOS

#69 [FE] Global Style 적용 Ver.2
  WEB/FE/src/index.tsx
  WEB/FE/tsconfig.json
Labels: FE

#71 [FE] ThemeProvider 추가
  WEB/BE/package-lock.json
  WEB/FE/package-lock.json
  WEB/FE/src/components/App.tsx
  WEB/FE/src/style/theme.ts
  WEB/FE/src/style/variable.ts
Labels: FE

#76 [FE] path alias 설정
  WEB/BE/.eslintrc.json
  WEB/FE/.eslintrc.json
  WEB/FE/tsconfig.json
  WEB/FE/webpack.common.js
Labels: FE

#73 [FE] Modal 컴포넌트 구현
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/common/Modal.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/style/GlobalStyle.ts
  WEB/FE/src/style/theme.ts
Labels: FE

#74 [BE] 회원가입,로그인 유효성 검사 미들웨어 추가
  WEB/BE/controllers/auth/index.js
  WEB/BE/jsconfig.json
  WEB/BE/middlewares/validator.js
  WEB/BE/package.json
  WEB/BE/routes/auth/index.js
  WEB/BE/routes/user/index.js
Labels: BE

#77 [BE] confirm E-mail 및 전송 API 구현
  WEB/BE/.env.template
  WEB/BE/controllers/email/index.js
  WEB/BE/controllers/user/index.js
  WEB/BE/package-lock.json
  WEB/BE/package.json
  WEB/BE/routes/user/index.js
  WEB/BE/services/auth/index.js
  WEB/BE/utils/crypto/index.js
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/confirmEmail/index.tsx
Labels: BE

#79 [iOS] 메인 검색 바 구현
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenListView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenListViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenViewModel.swift
Labels: iOS

#80 [FE] 회원가입 페이지 구현
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  WEB/FE/.eslintrc.json
  WEB/FE/package.json
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/components/common/Button.tsx
  WEB/FE/src/components/common/Input.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/pages/SignUpPage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/src/styles/GlobalStyle.ts
  WEB/FE/src/styles/theme.ts
  WEB/FE/tsconfig.json
  WEB/FE/webpack.common.js
Labels: FE

#81 [iOS] QRCode 뷰 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Info.plist
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainCellViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
Labels: iOS

#82 [FE] 회원가입 유효성 검사 및 설정코드 수정
  .github/PULL_REQUEST_TEMPLATE/be-pr.md
  .github/PULL_REQUEST_TEMPLATE/fe-pr.md
  .github/PULL_REQUEST_TEMPLATE/ios-pr.md
  WEB/BE/.eslintrc.json
  WEB/FE/.eslintrc.json
  WEB/FE/package-lock.json
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/components/common/Button.tsx
  WEB/FE/src/components/common/Input.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/style/GlobalStyle.ts
  WEB/FE/src/style/theme.ts
  WEB/FE/src/styles/GlobalStyle.ts
  WEB/FE/src/styles/theme.ts
  WEB/FE/src/utils/verify.ts
  WEB/FE/tsconfig.json
  WEB/FE/webpack.common.js
Labels: FE

#83 [FE] merge 과정에서 생긴 오류들 수정
  WEB/FE/.eslintrc.json
  WEB/FE/package-lock.json
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/components/common/Button.tsx
  WEB/FE/src/components/confirmEmail/index.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/pages/SignUpPage.tsx
Labels: FE

#85 [BE] 2주차 배포
  .env.enc
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/be-pr.md
  .github/PULL_REQUEST_TEMPLATE/ios-pr.md
  .travis.yml
  WEB/BE/.env.template
  WEB/BE/.eslintrc
  WEB/BE/.eslintrc.json
  WEB/BE/.prettierrc
  WEB/BE/.prettierrc.json
  WEB/BE/app.js
  WEB/BE/config/config.js
  WEB/BE/controllers/auth/index.js
  WEB/BE/controllers/email/index.js
  WEB/BE/controllers/user/index.js
  WEB/BE/jsconfig.json
  WEB/BE/middlewares/csrf.js
  WEB/BE/middlewares/validator.js
  WEB/BE/models/WEB/AUTHS.js
  WEB/BE/models/WEB/LOGS.js
  WEB/BE/models/WEB/USERS.js
  WEB/BE/models/iOS/DEVICES.js
  WEB/BE/models/iOS/TOKENS.js
  WEB/BE/models/iOS/USERS.js
  WEB/BE/models/redis/index.js
  WEB/BE/models/sequelizeIOS.js
  WEB/BE/models/sequelizeWEB.js
  WEB/BE/package-lock.json
  WEB/BE/package.json
  WEB/BE/routes/auth/index.js
  WEB/BE/routes/user/index.js
  WEB/BE/seeders/dummyDataWEB.js
  WEB/BE/services/auth/index.js
  WEB/BE/services/user/index.js
  WEB/BE/utils/bcrypt/index.js
  WEB/BE/utils/crypto/index.js
  WEB/FE/.eslintrc.json
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/components/common/Button.tsx
  WEB/FE/src/components/common/Input.tsx
  WEB/FE/src/components/common/Modal.tsx
  WEB/FE/src/components/confirmEmail/index.tsx
  WEB/FE/src/components/route/PrivateRoute.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/pages/SignUpPage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/src/styles/GlobalStyle.ts
  WEB/FE/src/styles/theme.ts
  WEB/FE/src/types/missingTypes.d.ts
  WEB/FE/src/utils/verify.ts
  WEB/FE/tsconfig.json
  WEB/FE/webpack.common.js
Labels: BE

#86 [BE] 2주차 배포
  .travis.yml
Labels: BE

#88 [iOS] 버그 수정 및 디테일 수정
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Extensions/Color+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenAddCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenViewModel.swift
Labels: iOS

#87 [iOS] TokenEditView 생성
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Extensions/View+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenViewModel.swift
Labels: iOS

#89 [FE]회원가입 페이지 API 및 QRCode 페이지 프로토타입 구현
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/pages/QRCodePage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/src/utils/verify.ts
Labels: FE

#91 [BE] 시간 값을 고정으로 두어서 API 요청 무시가 되는 경우 수정
  WEB/BE/controllers/email/index.js
  WEB/BE/controllers/user/index.js
Labels: BE, bug

#93 [WEB] : 경로 재설정 및 코드 수정
  WEB/BE/controllers/user/index.js
  WEB/FE/src/index.tsx
  WEB/FE/webpack.common.js
Labels: bug

#94 [BE] 2주차 배포
  WEB/BE/controllers/email/index.js
  WEB/BE/controllers/user/index.js
  WEB/BE/middlewares/reCAPTCHA.js
  WEB/BE/package-lock.json
  WEB/BE/package.json
  WEB/BE/routes/user/index.js
  WEB/BE/services/user/index.js
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/pages/QRCodePage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/src/utils/verify.ts
  WEB/FE/webpack.common.js
Labels: BE

#95 [FE] 2주차 배포
  .travis.yml
  WEB/BE/controllers/email/index.js
  WEB/BE/controllers/user/index.js
  WEB/BE/middlewares/reCAPTCHA.js
  WEB/BE/package-lock.json
  WEB/BE/package.json
  WEB/BE/routes/user/index.js
  WEB/BE/services/user/index.js
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/pages/QRCodePage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/src/utils/verify.ts
  WEB/FE/webpack.common.js
Labels: FE

#96 [iOS] TOTP generator, Timer 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/TOTPGenerator.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/TOTPTimer.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Model/Token.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainCellViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeonTests/TOTPGenerationTests.swift
  iOS/DaDaIkSeon/Podfile
  iOS/DaDaIkSeon/Podfile.lock
Labels: iOS

#101 [iOS] 아키텍쳐 관련 수정
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/xcuserdata/eozinee.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/ViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/MainService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
Labels: iOS

#97 [FE] Header, Footer 컴포넌트 추가
  WEB/FE/src/components/common/Footer.tsx
  WEB/FE/src/components/common/Header.tsx
  WEB/FE/src/styles/theme.ts
Labels: FE

#98 [FE] 레이아웃 컴포넌트 추가, 서버 배포 관련 에러 수정
  WEB/BE/models/sequelizeWEB.js
  WEB/BE/routes/user/index.js
  WEB/FE/package-lock.json
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/components/common/Modal.tsx
  WEB/FE/src/layouts/AuthPageLayout.tsx
  WEB/FE/src/layouts/MainPageLayout.tsx
  WEB/FE/src/pages/SignUpPage.tsx
  WEB/FE/src/static/undraw_unlock_24mb.svg
  WEB/FE/src/styles/GlobalStyle.ts
  WEB/FE/src/types/import-file.d.ts
  WEB/FE/tsconfig.json
  WEB/FE/webpack.common.js
Labels: FE

#99 [FE] login form 추가, login api 수정
  WEB/BE/controllers/auth/index.js
  WEB/BE/middlewares/reCAPTCHA.js
  WEB/BE/routes/auth/index.js
  WEB/BE/services/auth/index.js
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/LogIn/LogInForm.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/components/common/AuthForm.tsx
  WEB/FE/src/components/common/Button.tsx
  WEB/FE/src/components/common/Input.tsx
  WEB/FE/src/pages/LogInPage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/src/styles/GlobalStyle.ts
Labels: BE, FE

#100 [FE] web font 적용
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/index.tsx
  WEB/FE/src/styles/GlobalStyle.ts
  WEB/FE/src/styles/fonts/SpoqaHanSansBold.ttf
  WEB/FE/src/styles/fonts/SpoqaHanSansBold.woff
  WEB/FE/src/styles/fonts/SpoqaHanSansBold.woff2
  WEB/FE/src/styles/fonts/SpoqaHanSansLight.ttf
  WEB/FE/src/styles/fonts/SpoqaHanSansLight.woff
  WEB/FE/src/styles/fonts/SpoqaHanSansLight.woff2
  WEB/FE/src/styles/fonts/SpoqaHanSansRegular.ttf
  WEB/FE/src/styles/fonts/SpoqaHanSansRegular.woff
  WEB/FE/src/styles/fonts/SpoqaHanSansRegular.woff2
  WEB/FE/src/styles/fonts/SpoqaHanSansThin.ttf
  WEB/FE/src/styles/fonts/SpoqaHanSansThin.woff
  WEB/FE/src/styles/fonts/SpoqaHanSansThin.woff2
  WEB/FE/src/styles/theme.ts
  WEB/FE/src/styles/typography.css
  WEB/FE/webpack.common.js
Labels: FE

#103 [iOS] TokenCellViewModel 생성
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenCellViewModel.swift
Labels: iOS

#121 [Common] FE 폴더구조 리팩토링 및 에러 수정
  .travis.yml
  WEB/BE/routes/auth/index.js
  WEB/FE/config/webpack.common.js
  WEB/FE/config/webpack.dev.js
  WEB/FE/config/webpack.prod.js
  WEB/FE/package.json
  WEB/FE/src/api/index.tsx
  WEB/FE/src/pages/LogInPage.tsx
  WEB/FE/src/styles/GlobalStyle.ts
  WEB/FE/static/index.html
  WEB/FE/static/undraw_unlock_24mb.svg
Labels: BE, FE

#122 [FE] v1.0.0 배포
  .travis.yml
  WEB/BE/controllers/auth/index.js
  WEB/BE/middlewares/reCAPTCHA.js
  WEB/BE/models/sequelizeWEB.js
  WEB/BE/routes/auth/index.js
  WEB/BE/routes/user/index.js
  WEB/BE/services/auth/index.js
  WEB/FE/config/webpack.common.js
  WEB/FE/config/webpack.dev.js
  WEB/FE/config/webpack.prod.js
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/LogIn/LogInForm.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/components/common/AuthForm.tsx
  WEB/FE/src/components/common/Button.tsx
  WEB/FE/src/components/common/Footer.tsx
  WEB/FE/src/components/common/Header.tsx
  WEB/FE/src/components/common/Input.tsx
  WEB/FE/src/components/common/Modal.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/layouts/AuthPageLayout.tsx
  WEB/FE/src/layouts/MainPageLayout.tsx
  WEB/FE/src/pages/LogInPage.tsx
  WEB/FE/src/pages/SignUpPage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/src/styles/GlobalStyle.ts
  WEB/FE/src/styles/fonts/SpoqaHanSansBold.ttf
  WEB/FE/src/styles/fonts/SpoqaHanSansBold.woff
  WEB/FE/src/styles/fonts/SpoqaHanSansBold.woff2
  WEB/FE/src/styles/fonts/SpoqaHanSansLight.ttf
  WEB/FE/src/styles/fonts/SpoqaHanSansLight.woff
  WEB/FE/src/styles/fonts/SpoqaHanSansLight.woff2
  WEB/FE/src/styles/fonts/SpoqaHanSansRegular.ttf
  WEB/FE/src/styles/fonts/SpoqaHanSansRegular.woff
  WEB/FE/src/styles/fonts/SpoqaHanSansRegular.woff2
  WEB/FE/src/styles/fonts/SpoqaHanSansThin.ttf
  WEB/FE/src/styles/fonts/SpoqaHanSansThin.woff
  WEB/FE/src/styles/fonts/SpoqaHanSansThin.woff2
  WEB/FE/src/styles/theme.ts
  WEB/FE/src/styles/typography.css
  WEB/FE/src/types/import-file.d.ts
  WEB/FE/static/index.html
  WEB/FE/static/undraw_unlock_24mb.svg
  WEB/FE/tsconfig.json
  WEB/FE/webpack.common.js
Labels: FE

#123 [BE] v1.0.0 배포
  .travis.yml
  WEB/BE/controllers/auth/index.js
  WEB/BE/middlewares/reCAPTCHA.js
  WEB/BE/models/sequelizeWEB.js
  WEB/BE/routes/auth/index.js
  WEB/BE/routes/user/index.js
  WEB/BE/services/auth/index.js
  WEB/FE/config/webpack.common.js
  WEB/FE/config/webpack.dev.js
  WEB/FE/config/webpack.prod.js
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/LogIn/LogInForm.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/components/common/AuthForm.tsx
  WEB/FE/src/components/common/Button.tsx
  WEB/FE/src/components/common/Footer.tsx
  WEB/FE/src/components/common/Header.tsx
  WEB/FE/src/components/common/Input.tsx
  WEB/FE/src/components/common/Modal.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/layouts/AuthPageLayout.tsx
  WEB/FE/src/layouts/MainPageLayout.tsx
  WEB/FE/src/pages/LogInPage.tsx
  WEB/FE/src/pages/SignUpPage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/src/styles/GlobalStyle.ts
  WEB/FE/src/styles/fonts/SpoqaHanSansBold.ttf
  WEB/FE/src/styles/fonts/SpoqaHanSansBold.woff
  WEB/FE/src/styles/fonts/SpoqaHanSansBold.woff2
  WEB/FE/src/styles/fonts/SpoqaHanSansLight.ttf
  WEB/FE/src/styles/fonts/SpoqaHanSansLight.woff
  WEB/FE/src/styles/fonts/SpoqaHanSansLight.woff2
  WEB/FE/src/styles/fonts/SpoqaHanSansRegular.ttf
  WEB/FE/src/styles/fonts/SpoqaHanSansRegular.woff
  WEB/FE/src/styles/fonts/SpoqaHanSansRegular.woff2
  WEB/FE/src/styles/fonts/SpoqaHanSansThin.ttf
  WEB/FE/src/styles/fonts/SpoqaHanSansThin.woff
  WEB/FE/src/styles/fonts/SpoqaHanSansThin.woff2
  WEB/FE/src/styles/theme.ts
  WEB/FE/src/styles/typography.css
  WEB/FE/src/types/import-file.d.ts
  WEB/FE/static/index.html
  WEB/FE/static/undraw_unlock_24mb.svg
  WEB/FE/tsconfig.json
  WEB/FE/webpack.common.js
Labels: BE

#102 [FE]QR Code 페이지 구현
  WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/components/common/Input.tsx
  WEB/FE/src/pages/QRCodePage.tsx
  WEB/FE/src/styles/style.ts
Labels: FE
