Repository boostcamp-2020/Project03-A-TOTP, pull requests merged in 2020-12, with the labels that each got.

#125 [iOS] Service 계층 반영 아키텍처 리팩토링, 애니메이션 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainCellViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenCellViewModel.swift
Labels: iOS

#126 [WEB] Merge된 코드 Bug Fix
  WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/components/common/Button.tsx
  WEB/FE/src/components/common/Input.tsx
  WEB/FE/src/styles/style.ts
Labels: bug

#124 [BE] csrf header 방어 적용
  WEB/BE/app.js
  WEB/BE/middlewares/csrf.js
  WEB/FE/src/api/index.tsx
Labels: BE, FE

#131 [iOS] 큐알 코드 인식 성공시 편집 화면 표시
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
Labels: iOS

#132 [iOS] TokenEditView 수정, 파일 분리
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Extensions/Image+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenAddCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
Labels: iOS

#127 [FE] Storybook 환경설정
  WEB/FE/.storybook/main.js
  WEB/FE/.storybook/preview.js
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/stories/Introduction.stories.mdx
  WEB/FE/src/stories/Modal.stories.jsx
  WEB/FE/src/stories/assets/code-brackets.svg
  WEB/FE/src/stories/assets/colors.svg
  WEB/FE/src/stories/assets/comments.svg
  WEB/FE/src/stories/assets/direction.svg
  WEB/FE/src/stories/assets/flow.svg
  WEB/FE/src/stories/assets/plugin.svg
  WEB/FE/src/stories/assets/repo.svg
  WEB/FE/src/stories/assets/stackalt.svg
Labels: FE

#128 [FE] TOTP Modal 컴포넌트 추가, Button 컴포넌트 수정
  WEB/FE/.eslintrc.json
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/components/LogIn/LogInForm.tsx
  WEB/FE/src/components/TOTPModal/TOTPModal.tsx
  WEB/FE/src/components/common/AuthForm.tsx
  WEB/FE/src/components/common/Button.tsx
  WEB/FE/src/pages/LogInPage.tsx
  WEB/FE/src/styles/theme.ts
Labels: FE

#130 [BE] session 추가
  WEB/BE/app.js
  WEB/BE/middlewares/sessionAuthentication.js
  WEB/BE/models/redis/index.js
  WEB/BE/package-lock.json
  WEB/BE/package.json
Labels: BE

#133 [BE] validator 추가 구현
  WEB/BE/.eslintrc.json
  WEB/BE/middlewares/validator.js
  WEB/BE/middlewares/validator/config.js
  WEB/BE/middlewares/validator/index.js
  WEB/BE/middlewares/validator/validators.js
  WEB/BE/routes/auth/index.js
  WEB/BE/routes/user/index.js
Labels: BE

#136 [iOS] TokenEditView의 UI와 새 토큰을 등록하는 로직 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/NavigationLazyView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Extensions/Image+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Model/Token.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenEditViewModel.swift
Labels: iOS

#137 [iOS]메인 화면 다중 선택 삭제
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/ViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/ZeroTokenView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenCellViewModel.swift
Labels: iOS

#138 [iOS] 충돌 해결 Final
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
Labels: iOS

#134 [FE] 회원가입 페이지 리팩토링( Input 리팩토링)
  WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/components/common/Input.tsx
  WEB/FE/src/components/common/Input/DefaultInput.tsx
  WEB/FE/src/components/common/Input/EmailInput.tsx
  WEB/FE/src/components/common/Input/Form.tsx
  WEB/FE/src/components/common/Input/Input.ts
  WEB/FE/src/components/common/Input/PasswordInput.tsx
  WEB/FE/src/components/common/Input/PhoneInput.tsx
  WEB/FE/src/components/common/index.ts
  WEB/FE/src/hooks/index.ts
  WEB/FE/src/hooks/useInput.ts
  WEB/FE/src/utils/message.ts
  WEB/FE/src/utils/verify.ts
Labels: FE

#135 [BE] 아이디 찾기
  WEB/BE/controllers/email/index.js
  WEB/BE/controllers/user/index.js
  WEB/BE/routes/user/index.js
  WEB/BE/services/user/index.js
  WEB/BE/utils/email/index.js
Labels: BE

#142 [iOS] 추가/삭제 기능 머지 후 필요한 코드 추가
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/ZeroTokenView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
Labels: iOS

#139 [FE] login form, Input, Model 수정, 스토리 추가
  WEB/FE/package-lock.json
  WEB/FE/src/components/LogIn/LogInForm.tsx
  WEB/FE/src/components/common/AuthForm.tsx
  WEB/FE/src/components/common/Input/Form.tsx
  WEB/FE/src/components/common/Modal.tsx
  WEB/FE/src/stories/LogInForm.stories.jsx
  WEB/FE/src/stories/Modal.stories.jsx
  WEB/FE/src/stories/TOTPModal.stories.jsx
Labels: FE

#143 [FE] NotFoundPage 컴포넌트 추가 (404 페이지)
  WEB/FE/src/components/App.tsx
  WEB/FE/src/pages/NotFoundPage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/static/undraw_page_not_found_su7k.svg
Labels: FE

#144 [BE] 외부 lib없이 TOTP 미들웨어 구현
  WEB/BE/controllers/user/index.js
  WEB/BE/utils/totp/index.js
Labels: BE

#145 [FE] 아이디 찾기 페이지 구현
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/findID/findIDComponent.tsx
  WEB/FE/src/pages/findIDPage.tsx
  WEB/FE/src/pages/index.tsx
Labels: BE

#146 [BE] session login시 연결
  WEB/BE/app.js
  WEB/BE/controllers/auth/index.js
  WEB/BE/middlewares/sessionAuthentication.js
Labels: BE

#147 [FE] 로그인 api 응답 처리
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/components/LogIn/LogInForm.tsx
  WEB/FE/src/components/TOTPModal/TOTPModal.tsx
  WEB/FE/src/components/common/Modal.tsx
Labels: FE

#148 [BE] 비밀번호 찾기 이메일 전송 함수 구현
  WEB/BE/controllers/auth/index.js
  WEB/BE/package.json
  WEB/BE/services/auth/index.js
  WEB/BE/services/user/index.js
  WEB/BE/utils/email/index.js
Labels: BE

#149 [BE] TOTP 6자리 검증 API 및 미들웨어 구현
  WEB/BE/controllers/auth/index.js
  WEB/BE/middlewares/verifyJWT.js
  WEB/BE/routes/auth/index.js
  WEB/BE/utils/totp/index.js
Labels: BE

#150 [FE] 비밀번호 변경 페이지
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/ChangePass/ChangePasswordComponent.tsx
  WEB/FE/src/components/findID/findIDComponent.tsx
  WEB/FE/src/pages/ChangePasswordPage.tsx
  WEB/FE/src/pages/index.tsx
Labels: FE

#151 [BE] TOTP 검증 API 수정
  WEB/BE/controllers/auth/index.js
  WEB/BE/middlewares/verifyJWT.js
  WEB/BE/utils/totp/index.js
Labels: BE

#152 [BE] 비밀번호 찾기- 변경된 비밀번호 전송 API
  WEB/BE/controllers/auth/index.js
  WEB/BE/routes/auth/index.js
  WEB/BE/services/auth/index.js
Labels: BE

#154 [FE] 비밀번호 찾기 페이지 구현
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/FindPassword/FindPasswordContainer.tsx
  WEB/FE/src/components/FindPassword/FindPasswordForm.tsx
  WEB/FE/src/components/common/Input/EmailInput.tsx
  WEB/FE/src/pages/FindPasswordPage.tsx
  WEB/FE/src/pages/index.tsx
Labels: FE

#155 [BE] Email path 변경
  WEB/BE/utils/email/index.js
Labels: BE

#153 [iOS] 버그들 수정
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
Labels: iOS

#167 [FE] github action 배포
  .github/workflows/FE.deploy.yml
  WEB/BE/package-lock.json
  WEB/BE/routes/auth/index.js
Labels: FE

#168 [FE] 배포 테스트
  WEB/FE/src/components/App.tsx
Labels: FE

#169 [BE] github actions 배포 테스트
  .github/workflows/BE.deploy.yml
  .github/workflows/FE.deploy.yml
  WEB/FE/src/components/App.tsx
Labels: BE

#170 [BE] 배포 테스트
  .github/workflows/BE.deploy.yml
  WEB/BE/app.js
Labels: BE

#171 [BE] 배포 테스트
  .github/workflows/BE.deploy.yml
Labels: BE

#172 [BE] 배포 테스트
  .github/workflows/BE.deploy.yml
  .github/workflows/FE.deploy.yml
Labels: BE

#173 [FE] 배포 테스트
  .github/workflows/BE.deploy.yml
  .github/workflows/FE.deploy.yml
  WEB/BE/app.js
Labels: FE

#178 [iOS] 타이머로 인한 에딧뷰 무한 init 문제 해결
  iOS/DaDaIkSeon/DaDaIkSeon/Common/TOTPTimer.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenCellViewModel.swift
Labels: iOS

#177 [iOS] 서치바 버그 수정
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
Labels: iOS

#180 [iOS] 네비게이션 링크로 화면전환 시에도 타이머 On/Off
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
Labels: iOS

#179 [iOS] search 중 cell로 돌아갔을 때 TextField 버그 수정
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenCellViewModel.swift
Labels: iOS

#181 [iOS] 키체인 붙이기
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/StorageManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Model/Token.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
Labels: iOS

#184 [iOS] Token 수정하기
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Info.plist
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/MockTokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenServiceable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenCellViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenEditViewModel.swift
Labels: iOS

#185 [iOS] Service 키체인 불러오기 버그 수정, 조금 생각해볼 애니메이션 추가
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
Labels: iOS

#190 [iOS] 셀 애니메이션(이동, 춤추기) 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Color+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Double+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Image+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/View+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Util/NavigationFlowObject.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Util/NavigationLazyView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/Usecase/MainUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/TokenAddCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/TokenDropDelegate.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/ZeroTokenView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Model/Token.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/MockTokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/TokenServiceable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenCellView/View/TokenCellView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenCellView/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenCellView/ViewModel/TokenCellViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenEditView/View/TokenEditView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenEditView/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenEditView/ViewModel/TokenEditViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeonTests/DaDaIkSeonTests.swift
  iOS/DaDaIkSeon/DaDaIkSeonTests/TOTPGenerator/DDISTOTPGeneratorTests.swift
  iOS/DaDaIkSeon/DaDaIkSeonTests/TOTPGenerator/TOTPGenerationTests.swift
Labels: iOS

#192 [iOS] 메인 뷰모델 정리
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/Usecase/MainUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/ViewModel/CellHandler.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/ViewModel/CheckBoxHandler.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/ViewModel/Handlerable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/ViewModel/SearchHandler.swift
Labels: iOS

#186 [BE] 시크릿 키 재발급 이메일 전송 API
  WEB/BE/controllers/auth/index.js
  WEB/BE/controllers/user/index.js
  WEB/BE/routes/auth/index.js
  WEB/BE/utils/emailSender/index.js
Labels: BE

#176 [Common] travis 제거
  .env.enc
  .travis.yml
  deploy_rsa.enc
Labels: BE, FE

#183 [Common] Swagger 적용 및 api 문서 작성
  WEB/BE/app.js
  WEB/BE/config/swagger.js
  WEB/BE/jsconfig.json
  WEB/BE/package-lock.json
  WEB/BE/package.json
  WEB/BE/routes/auth/index.js
  package-lock.json
Labels: BE, FE

#187 [FE] api 리팩토링
  WEB/BE/controllers/auth/index.js
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
Labels: FE

#188 [BE] 에러 핸들링 리팩토링
  WEB/BE/controllers/auth/index.js
  WEB/BE/controllers/user/index.js
  WEB/BE/routes/auth/index.js
  WEB/BE/routes/user/index.js
  WEB/BE/services/auth/index.js
  WEB/BE/services/user/index.js
  WEB/BE/utils/util/index.js
Labels: BE

#193 [iOS] LoginView 생성
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/background.imageset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/background.imageset/background.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/background.imageset/background@2x.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/background.imageset/background@3x.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Info.plist
  iOS/DaDaIkSeon/DaDaIkSeon/Login/View/LoginView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Login/ViewModel/LoginViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenCell/View/TokenCellView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenCell/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenCell/ViewModel/TokenCellViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenEdit/View/TokenEditView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenEdit/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenEdit/ViewModel/TokenEditViewModel.swift
Labels: iOS

#189 [BE] CSRF Token 적용
  WEB/BE/controllers/auth/index.js
  WEB/BE/middlewares/sessionAuthentication.js
  WEB/BE/services/log/index.js
  WEB/BE/utils/random/index.js
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/FindPassword/FindPasswordContainer.tsx
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/utils/message.ts
Labels: BE

#191 [BE] Session Middleware 적용
  WEB/BE/middlewares/index.js
  WEB/BE/middlewares/reCAPTCHA.js
  WEB/BE/routes/auth/index.js
  WEB/BE/routes/user/index.js
Labels: BE

#194 [iOS] 배포 전 수정
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/xcshareddata/xcschemes/DaDaIkSeon.xcscheme
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/darkNavy.colorset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Color+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Info.plist
  iOS/DaDaIkSeon/DaDaIkSeon/Main/Usecase/MainUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenAddCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenDropDelegate.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/View/ZeroTokenView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/CellHandler.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/CheckBoxHandler.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/Handlerable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/SearchHandler.swift
  iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/ZeroTokenView.swift
Labels: iOS

#208 [iOS] app icon 추가, Token model 수정
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/100.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/1024.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/114.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/120.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/172.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/180.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/196.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/216.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/29.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/40.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/48.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/55.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/57.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/58.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/60.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/80.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/87.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/88.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/background.imageset/background.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/background.imageset/background@2x.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/background.imageset/background@3x.png
  iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/SearchHandler.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Model/Token.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenCell/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenEdit/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/TokenEdit/ViewModel/TokenEditViewModel.swift
Labels: iOS

#195 [BE] TOTP 재발급 새로운 Key 생성
  WEB/BE/controllers/auth/index.js
  WEB/BE/services/auth/index.js
  WEB/BE/utils/emailSender/index.js
Labels: BE

#209 [FE] MyPage 컴포넌트
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
  WEB/FE/src/components/PrivateRoute/PrivateRoute.tsx
  WEB/FE/src/layouts/MainPageLayout.tsx
  WEB/FE/src/pages/MyPage.tsx
  WEB/FE/src/pages/NotFoundPage.tsx
  WEB/FE/src/pages/index.tsx
Labels: FE

#210 [FE] MyInfo, MyInfoEdit 컴포넌트
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/components/MyPage/MyInfo.tsx
  WEB/FE/src/components/MyPage/MyInfoEdit.tsx
  WEB/FE/src/components/common/Description.tsx
Labels: FE

#211 [FE] AccessLog, Table 컴포넌트
  WEB/FE/src/components/MyPage/AccessLog.tsx
  WEB/FE/src/components/common/Table.tsx
Labels: FE

#212 [FE,BE] TOTP 재발급 기능
  WEB/BE/controllers/auth/index.js
  WEB/BE/routes/auth/index.js
  WEB/BE/services/auth/index.js
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/components/TOTPModal/TOTPModal.tsx
  WEB/FE/src/utils/message.ts
Labels: BE, FE

#214 [iOS] setting 뷰 추가, 그룹 정리
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/ddLogo.imageset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/ddLogo.imageset/ddLogo.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/ddLogo.imageset/ddLogo@2x.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/ddLogo.imageset/ddLogo@3x.png
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/ViewModel/LoginViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/Usecase/MainUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/SearchBarView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/TokenAddCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/TokenDropDelegate.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/ZeroTokenView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/CellHandler.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/CheckBoxHandler.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/SearchHandler.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenCell/View/TokenCellView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenCell/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenCell/ViewModel/TokenCellViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenEdit/View/TokenEditView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenEdit/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenEdit/ViewModel/TokenEditViewModel.swift
Labels: iOS

#215 [BE] Log model 변경
  WEB/BE/models/WEB/AUTHS.js
  WEB/BE/models/WEB/LOGS.js
  WEB/BE/models/WEB/USERS.js
  WEB/BE/seeders/dummyDataWEB.js
Labels: BE

#216 [FE] 내정보 조회, 수정 api 적용
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
Labels: FE

#217 [BE] 내 정보 조회, 수정 API 추가
  WEB/BE/controllers/user/index.js
  WEB/BE/middlewares/sessionAuthentication.js
  WEB/BE/routes/user/index.js
  WEB/BE/services/auth/index.js
Labels: BE

#218 [BE] 비밀번호 확인 API, 접속기록 추가
  WEB/BE/controllers/auth/index.js
  WEB/BE/package-lock.json
  WEB/BE/package.json
  WEB/BE/routes/auth/index.js
  WEB/BE/services/log/index.js
Labels: BE

#219 [BE] redis 이벤트를 통한 자동 만료 확인 및 모델 수정
  WEB/BE/config/config.js
  WEB/BE/controllers/user/index.js
  WEB/BE/models/WEB/AUTHS.js
  WEB/BE/models/WEB/LOGS.js
  WEB/BE/models/redis/index.js
  WEB/BE/seeders/dummyDataWEB.js
  WEB/BE/services/auth/index.js
  WEB/BE/services/log/index.js
Labels: BE

#220 [BE] 내정보 조회, 수정 api 수정, 리팩토링
  WEB/BE/controllers/auth/index.js
  WEB/BE/controllers/user/index.js
  WEB/BE/middlewares/sessionAuthentication.js
  WEB/BE/services/auth/index.js
Labels: BE

#224 [iOS] LoginView UI, ViewModel, Service 추가
  iOS/DaDaIkSeon/.swiftlint.yml
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Image+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/Usecase/LoginUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginCodeView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/ViewModel/LoginViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/ZeroTokenView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenCell/Usecase/TokenCellUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenCell/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenEdit/Usecase/TokenEditUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenEdit/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Login/LoginService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/MockTokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenServiceable.swift
Labels: iOS

#226 [iOS] 네트워킹에 필요한 코드 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Network/EndpointType.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/HTTPMethod.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/NetworkResult.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Requestable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/ResponseArray.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/ResponseObject.swift
Labels: iOS

#225 [iOS] Setting View 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Image+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Model/DDISUser.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Model/Device.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingViewComponents/SettingGridView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingViewComponents/SettingRow.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingViewComponents/SettingViewWrapper.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/SettingServicaeble.swift
Labels: iOS

#221 [FE] MyPage에 Check Password Modal 적용
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
  WEB/FE/src/components/PasswordModal/PasswordModal.tsx
Labels: FE

#222 [BE] 접속 디바이스 만료 - 사용자 요청에 의해 만료
  WEB/BE/app.js
  WEB/BE/controllers/log/index.js
  WEB/BE/middlewares/sessionAuthentication.js
  WEB/BE/models/redis/index.js
  WEB/BE/routes/log/index.js
Labels: BE

#223 [FE] 마이페이지 에러 핸들링 추가
  WEB/FE/.eslintrc.json
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
Labels: FE

#228 [FE] Header구현, theme 수정
  WEB/FE/src/components/MyPage/AccessLog.tsx
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
  WEB/FE/src/components/common/Button.tsx
  WEB/FE/src/components/common/Description.tsx
  WEB/FE/src/components/common/Footer.tsx
  WEB/FE/src/components/common/Header.tsx
  WEB/FE/src/components/common/Input/Form.tsx
  WEB/FE/src/components/common/Modal.tsx
  WEB/FE/src/components/common/Table.tsx
  WEB/FE/src/styles/theme.ts
  WEB/FE/static/logo.svg
Labels: FE

#227 [FE,BE] 페이지네이션된 로그데이터 전달 및 보여주기
  WEB/BE/app.js
  WEB/BE/controllers/auth/index.js
  WEB/BE/controllers/log/index.js
  WEB/BE/routes/log/index.js
  WEB/BE/services/log/index.js
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/MyPage/AccessLog.tsx
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
Labels: BE, FE

#232 [iOS] PinCodeView UI 개발
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Image+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Info.plist
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/ZeroTokenView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/PinCodeView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
Labels: iOS

#233 [iOS] 세팅 화면 편집 기능 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Image+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/SettingServicaeble.swift
Labels: iOS

#234 [iOS] fix: File Reference Bug 고침
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
Labels: iOS

#231 [FE][BE] 사용자에 의한 session 만료
  WEB/BE/controllers/log/index.js
  WEB/BE/models/WEB/LOGS.js
  WEB/BE/routes/log/index.js
  WEB/BE/services/log/index.js
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/MyPage/AccessLog.tsx
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
Labels: BE, FE

#235 [BE] iOS 모델 수정, iOS api 구현 : /app/user
  WEB/BE/app.js
  WEB/BE/config/config.js
  WEB/BE/controllers/iOS/device/index.js
  WEB/BE/controllers/iOS/user/index.js
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/controllers/web/log/index.js
  WEB/BE/controllers/web/user/index.js
  WEB/BE/middlewares/verifyJWT.js
  WEB/BE/models/iOS/DEVICES.js
  WEB/BE/models/iOS/TOKENS.js
  WEB/BE/models/iOS/USERS.js
  WEB/BE/models/redis/index.js
  WEB/BE/models/sequelizeIOS.js
  WEB/BE/routes/iOS/index.js
  WEB/BE/routes/iOS/user/index.js
  WEB/BE/routes/web/auth/index.js
  WEB/BE/routes/web/log/index.js
  WEB/BE/routes/web/user/index.js
  WEB/BE/services/iOS/device/index.js
  WEB/BE/services/iOS/user/index.js
  WEB/BE/services/web/auth/index.js
  WEB/BE/services/web/log/index.js
  WEB/BE/services/web/user/index.js
Labels: BE

#236 [FE] 로그인페이지, 라우터 변경
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/components/LogIn/LogInForm.tsx
  WEB/FE/src/components/PrivateRoute/PrivateRoute.tsx
  WEB/FE/src/pages/MyPage.tsx
Labels: FE

#246 [FE] 로그인 상태에 따라 헤더 정보 수정
  WEB/BE/controllers/web/auth/index.js
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/components/PrivateRoute/PrivateRoute.tsx
  WEB/FE/src/components/common/Header.tsx
  WEB/FE/src/components/common/Header/Dropdown.tsx
  WEB/FE/src/components/common/Header/Header.tsx
  WEB/FE/src/components/common/Header/Nav.tsx
  WEB/FE/src/layouts/MainPageLayout.tsx
  WEB/FE/src/utils/localStorage.ts
Labels: BE, FE

#247 [FE,BE] 세션 에러처리 수정
  WEB/BE/middlewares/sessionAuthentication.js
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
Labels: BE, FE

#249 [FE] ChangeTimeView
  WEB/FE/src/components/MyPage/AccessLog.tsx
Labels: FE

#251 [iOS] QR
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/dadaikseonQR.imageset/Contents.json
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/dadaikseonQR.imageset/dadaikseonQR.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/dadaikseonQR.imageset/dadaikseonQR@2x.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Assets.xcassets/dadaikseonQR.imageset/dadaikseonQR@3x.png
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Image+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/TOTPTimer.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Model/DDISUser.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
Labels: iOS

#253 [FE,BE]로그아웃 (세션, 쿠키, Local Storage) 삭제 구현
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/routes/web/auth/index.js
  WEB/FE/src/api/index.tsx
  WEB/FE/src/components/common/Header/Header.tsx
Labels: BE, FE

#255 [BE] iOS Token CRUD Router, Controller, Service 구현하기
  WEB/BE/controllers/iOS/token/index.js
  WEB/BE/routes/iOS/index.js
  WEB/BE/routes/iOS/token/index.js
  WEB/BE/services/iOS/token/index.js
  WEB/BE/services/iOS/user/index.js
Labels: BE

#262 [BE]이메일 인증 체크 구현
  WEB/BE/controllers/web/auth/index.js
Labels: BE

#263 [BE] iOS 인증 6자리 생성 및 이메일 전송
  WEB/BE/controllers/iOS/user/index.js
  WEB/BE/utils/emailSender/index.js
  WEB/BE/utils/random/index.js
Labels: BE

#264 [BE] redis event 수신
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/models/redis/index.js
Labels: BE

#266 [BE] iOS 토큰API (Sync 맞추기)
  WEB/BE/config/swagger.js
  WEB/BE/controllers/iOS/token/index.js
  WEB/BE/routes/iOS/token/index.js
  WEB/BE/services/iOS/token/index.js
  WEB/BE/services/iOS/user/index.js
Labels: BE

#267 [FE] Index 페이지 구현
  WEB/FE/src/components/IndexPage/Banner.tsx
  WEB/FE/src/components/IndexPage/IndexPageContainer.tsx
  WEB/FE/src/components/IndexPage/Section.tsx
  WEB/FE/src/components/common/Header/Dropdown.tsx
  WEB/FE/src/types/import-file.d.ts
  WEB/FE/static/john-tuesday-8c6iJMh80BI-unsplash.jpg
  WEB/FE/static/undraw_mobile_web_2g8b.svg
  WEB/FE/static/undraw_security_o890.svg
Labels: FE

#269 [BE] 4주차 배포
  WEB/BE/config/swagger.js
  WEB/BE/controllers/iOS/token/index.js
  WEB/BE/controllers/iOS/user/index.js
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/models/redis/index.js
  WEB/BE/routes/iOS/token/index.js
  WEB/BE/services/iOS/token/index.js
  WEB/BE/services/iOS/user/index.js
  WEB/BE/utils/emailSender/index.js
  WEB/BE/utils/random/index.js
  WEB/FE/src/components/IndexPage/Banner.tsx
  WEB/FE/src/components/IndexPage/IndexPageContainer.tsx
  WEB/FE/src/components/IndexPage/Section.tsx
  WEB/FE/src/components/common/Header/Dropdown.tsx
  WEB/FE/src/types/import-file.d.ts
  WEB/FE/static/john-tuesday-8c6iJMh80BI-unsplash.jpg
  WEB/FE/static/undraw_mobile_web_2g8b.svg
  WEB/FE/static/undraw_security_o890.svg
Labels: BE

#270 [FE] 4주차 배포
  WEB/BE/config/swagger.js
  WEB/BE/controllers/iOS/token/index.js
  WEB/BE/controllers/iOS/user/index.js
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/models/redis/index.js
  WEB/BE/routes/iOS/token/index.js
  WEB/BE/services/iOS/token/index.js
  WEB/BE/services/iOS/user/index.js
  WEB/BE/utils/emailSender/index.js
  WEB/BE/utils/random/index.js
  WEB/FE/src/components/IndexPage/Banner.tsx
  WEB/FE/src/components/IndexPage/IndexPageContainer.tsx
  WEB/FE/src/components/IndexPage/Section.tsx
  WEB/FE/src/components/common/Header/Dropdown.tsx
  WEB/FE/src/types/import-file.d.ts
  WEB/FE/static/john-tuesday-8c6iJMh80BI-unsplash.jpg
  WEB/FE/static/undraw_mobile_web_2g8b.svg
  WEB/FE/static/undraw_security_o890.svg
Labels: FE

#265 [iOS] 네트워크 API 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Model/DDISUser.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Model/Device.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Model/Token.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/EndpointType.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/HTTPMethod.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/NetworkResult.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/Requestable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/ResponseArray.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/ResponseObject.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingEndpoint.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenEndpoint.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/JWTNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserEndpoint.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
Labels: iOS

#268 [iOS] 생체인증
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/BiometricIDAuthManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/PincodeManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/QRGuideView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/PinCodeView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingViewComponents/SettingRow.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/SettingServicaeble.swift
  iOS/DaDaIkSeon/DaDaIkSeonTests/UtilTest/DateFormatTest.swift
Labels: iOS

#286 [iOS] 생체인증 완성, 키체인 삭제 버그 수정
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/PinCodeView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenCell/View/TokenCellView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
Labels: iOS

#290 [FE,BE]비밀번호 변경 오류 해결 및 이메일 인증 후 알림 구현
  WEB/BE/controllers/web/auth/index.js
  WEB/FE/src/api/index.ts
  WEB/FE/src/components/ChangePass/ChangePasswordComponent.tsx
  WEB/FE/src/components/confirmEmail/index.tsx
  WEB/FE/src/utils/message.ts
Labels: BE, FE

#288 [iOS] User이메일 api 붙이기
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Image+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/String+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Info.plist
  iOS/DaDaIkSeon/DaDaIkSeon/Model/JWTToken.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/EndpointType.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/Requestable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/JWTNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserEndpoint.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/Usecase/LoginUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginCodeView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/ViewModel/LoginViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenCell/View/TokenCellView+SubViews.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenCell/ViewModel/TokenCellViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenEdit/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Login/LoginService.swift
Labels: iOS

#291 [iOS] inactive 배경 설정, 프로그레스바 반대 방향으로 변경
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Image+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenCell/View/TokenCellView+SubViews.swift
Labels: iOS

#295 [iOS] 설정화면 네트워크 추가
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/String+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/LocalStorageManager/BackupPasswordManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/TokenCryptoManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Util/Entry.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Views/BackgroundView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/Requestable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingEndpoint.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/JWTNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView+Views/SettingView+BackupSetting.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView+Views/SettingView+DeviceSetting.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView+Views/SettingView+MyInfoSetting.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingViewComponents/SettingToggleView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+AuthMode.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+Backup.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+Email.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+MultiDevice.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenEdit/View/TokenEditView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Login/LoginService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/SettingServicaeble.swift
Labels: iOS

#292 [BE] iOS Model, API 수정
  WEB/BE/controllers/iOS/user/index.js
  WEB/BE/models/iOS/DEVICES.js
  WEB/BE/models/iOS/USERS.js
Labels: BE

#293 [FE] react-helmet적용, favicon 추가
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/index.tsx
  WEB/FE/static/favicon.ico
Labels: FE

#296 [FE] 서브페이지 추가
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/IndexPage/IndexPageContainer.tsx
  WEB/FE/src/components/TOTPIntro/TOTPIntroContainer.tsx
  WEB/FE/src/components/Why2FA/Why2FAContainer.tsx
  WEB/FE/src/components/common/Header/Nav.tsx
  WEB/FE/src/components/common/Paragraph.tsx
  WEB/FE/src/components/common/Section/BlockSection.tsx
  WEB/FE/src/components/common/index.ts
  WEB/FE/src/pages/TOTPIntroPage.tsx
  WEB/FE/src/pages/Why2FAPage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/static/undraw_two_factor_authentication_namy.svg
Labels: FE

#298 [BE] app/user swagger 문서 작성
  WEB/BE/config/swagger.js
  WEB/BE/routes/iOS/user/index.js
Labels: BE

#297 [BE] Swagger iOS/Token 작성
  WEB/BE/controllers/iOS/token/index.js
  WEB/BE/routes/iOS/token/index.js
Labels: BE

#299 [iOS] SettingView 정리
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/String+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Util/KeboardModifier.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Model/Device.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView+Views/SettingView+BackupSetting.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView+Views/SettingView+DeviceSetting.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView+Views/SettingView+MyInfoSetting.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingViewComponents/SettingErrorMessageView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingViewComponents/SettingViewWrapper.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+Backup.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+MultiDevice.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/SettingServicaeble.swift
Labels: iOS

#300 [iOS] 로그인과 메인 합치기
  iOS/DaDaIkSeon/.swiftlint.yml
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/AppDelegate.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Info.plist
  iOS/DaDaIkSeon/DaDaIkSeon/Common/JWTTokenStoreManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Views/BackgroundView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/NetworkResult.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/JWTNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/Usecase/LoginUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginCodeView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/ViewModel/LoginViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/PinCodeView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Login/LoginService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/SettingServicaeble.swift
Labels: iOS

#304 [BE] Swagger session 인증 방법 추가
  WEB/BE/config/swagger.js
  WEB/BE/routes/iOS/token/index.js
  WEB/BE/routes/iOS/user/index.js
  WEB/BE/routes/web/auth/index.js
  WEB/BE/routes/web/log/index.js
  WEB/BE/routes/web/user/index.js
  WEB/BE/services/iOS/token/index.js
Labels: BE

#316 [BE] iOS api 추가 및 수정
  WEB/BE/controllers/iOS/user/index.js
  WEB/BE/routes/iOS/user/index.js
Labels: BE

#315 [BE] iOS token API swagger 파라미터 오류 수정
  WEB/BE/controllers/iOS/token/index.js
  WEB/BE/routes/iOS/token/index.js
  WEB/BE/services/iOS/token/index.js
Labels: BE

#317 [BE] iOS api 수정
  WEB/BE/controllers/iOS/device/index.js
  WEB/BE/controllers/iOS/user/index.js
  WEB/BE/routes/iOS/user/index.js
Labels: BE

#318 [BE] iOS 테스트를 위한 배포
  WEB/BE/config/swagger.js
  WEB/BE/controllers/iOS/device/index.js
  WEB/BE/controllers/iOS/token/index.js
  WEB/BE/controllers/iOS/user/index.js
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/models/iOS/DEVICES.js
  WEB/BE/models/iOS/USERS.js
  WEB/BE/routes/iOS/token/index.js
  WEB/BE/routes/iOS/user/index.js
  WEB/BE/routes/web/auth/index.js
  WEB/BE/routes/web/log/index.js
  WEB/BE/routes/web/user/index.js
  WEB/BE/services/iOS/token/index.js
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/api/index.ts
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/ChangePass/ChangePasswordComponent.tsx
  WEB/FE/src/components/IndexPage/IndexPageContainer.tsx
  WEB/FE/src/components/TOTPIntro/TOTPIntroContainer.tsx
  WEB/FE/src/components/Why2FA/Why2FAContainer.tsx
  WEB/FE/src/components/common/Header/Nav.tsx
  WEB/FE/src/components/common/Paragraph.tsx
  WEB/FE/src/components/common/Section/BlockSection.tsx
  WEB/FE/src/components/common/index.ts
  WEB/FE/src/components/confirmEmail/index.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/pages/TOTPIntroPage.tsx
  WEB/FE/src/pages/Why2FAPage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/src/utils/message.ts
  WEB/FE/static/favicon.ico
  WEB/FE/static/undraw_two_factor_authentication_namy.svg
Labels: BE

#312 [BE] Email 재전송 추가
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/controllers/web/user/index.js
  WEB/BE/routes/web/user/index.js
Labels: BE

#313 [FE] Email 재전송 추가
  WEB/FE/src/api/index.ts
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/components/LogIn/LogInForm.tsx
Labels: FE

#314 [BE] 한스탭 앞 OTP 정보도 사용 가능
  WEB/BE/utils/totp/index.js
Labels: BE

#319 [FE] iOS API 수정
  WEB/BE/controllers/iOS/user/index.js
Labels: BE

#322 [FE] 서브페이지/학습하기 페이지 구현
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/StudyComponent/DragAndDrop/Drag.tsx
  WEB/FE/src/components/StudyComponent/DragAndDrop/DropTarget.tsx
  WEB/FE/src/components/StudyComponent/MarkButton/MarkButton.tsx
  WEB/FE/src/components/StudyComponent/StudyBox/StudyBox.tsx
  WEB/FE/src/components/StudyComponent/StudyComponent.tsx
  WEB/FE/src/components/common/Header/Nav.tsx
  WEB/FE/src/pages/StudyPage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/src/utils/initialData.ts
  WEB/FE/static/HMAC.svg
  WEB/FE/static/OTP.svg
  WEB/FE/static/SecretKey.svg
  WEB/FE/static/TOTPFrame.svg
  WEB/FE/static/TimeStamp.svg
  WEB/FE/static/Truncation.svg
Labels: FE

#320 [iOS] Login API 수정
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/Requestable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserEndpoint.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/Usecase/BackupPasswordUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/View/BackupPasswordView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/ViewModel/BackupPaswordViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/Usecase/LoginNetworkResult.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/Usecase/LoginUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginCodeView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/ViewModel/LoginViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/Usecase/MainUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/MainView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Login/LoginService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/SettingServicaeble.swift
Labels: iOS

#323 [iOS] Setting API 수정
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Model/DDISUser.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/NetworkResult.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingNetworkResult.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+Backup.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+Email.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+MultiDevice.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/SettingServicaeble.swift
Labels: iOS

#324 [BE] iOS API, Model 수정
  WEB/BE/controllers/iOS/user/index.js
  WEB/BE/models/iOS/DEVICES.js
  WEB/BE/routes/iOS/user/index.js
Labels: BE

#326 [BE] HMAC 리팩토링 및 적용
  WEB/BE/utils/crypto/index.js
  WEB/BE/utils/totp/hmac.js
  WEB/BE/utils/totp/index.js
Labels: BE

#327 [BE] totp 반복 로그인 제한
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/middlewares/verifyJWT.js
  WEB/BE/models/WEB/AUTHS.js
  WEB/BE/services/web/auth/index.js
Labels: BE

#328 [BE] Helmet 적용
  WEB/BE/app.js
  WEB/BE/package-lock.json
  WEB/BE/package.json
Labels: BE

#335 [iOS] token refresh
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/AppDelegate.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/TokenCryptoManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Model/DDISUser.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/Usecase/MainNetworkResult.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/MockTokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenServiceable.swift
Labels: iOS

#336 [iOS] backupPasswordView service주입
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Model/DDISUser.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/Usecase/BackupPasswordUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/View/BackupPasswordView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/ViewModel/BackupPaswordViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginCodeView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/ViewModel/LoginViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/MainView.swift
Labels: iOS

#329 [FE] 서브페이지 구현 - totp-intro
  WEB/FE/src/components/TOTPIntro/TOTPIntroContainer.tsx
  WEB/FE/src/components/Why2FA/Why2FAContainer.tsx
  WEB/FE/src/components/common/Paragraph.tsx
  WEB/FE/src/components/common/Section/BlockSection.tsx
  WEB/FE/src/types/import-file.d.ts
  WEB/FE/static/640px-SHAhmac.png
  WEB/FE/static/totp-diagram.png
Labels: FE

#334 [FE] 버그 수정, Header, Footer, Tab 수정
  WEB/FE/src/components/Footer/Footer.tsx
  WEB/FE/src/components/MyPage/AccessLog.tsx
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
  WEB/FE/src/components/common/Header/Dropdown.tsx
  WEB/FE/src/components/common/Header/Header.tsx
  WEB/FE/src/layouts/MainPageLayout.tsx
  WEB/FE/static/github.svg
Labels: FE

#330 [BE] TOTP TOTP 5번 이상 미일치시 제한
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/controllers/web/user/index.js
  WEB/BE/middlewares/verifyJWT.js
  WEB/BE/models/WEB/AUTHS.js
  WEB/BE/routes/iOS/token/index.js
  WEB/BE/services/web/auth/index.js
Labels: BE

#333 [FE] 로그인 5회 실패시 다시 로그인 및 Email 전송 알림
  WEB/FE/src/components/LogIn/LogInContainer.tsx
Labels: FE

#332 [FE] Axios Interceptor 설정 및 SessionAuthentication 리팩토링
  WEB/BE/middlewares/sessionAuthentication.js
  WEB/FE/src/api/config.ts
  WEB/FE/src/api/index.ts
Labels: BE, FE

#337 [FE] QRCode Page Refactoring
  WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
  WEB/FE/src/pages/QRCodePage.tsx
Labels: FE

#338 [BE] 기능구현 후 1차 배포
  WEB/BE/app.js
  WEB/BE/controllers/iOS/user/index.js
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/controllers/web/user/index.js
  WEB/BE/middlewares/sessionAuthentication.js
  WEB/BE/middlewares/verifyJWT.js
  WEB/BE/models/WEB/AUTHS.js
  WEB/BE/models/iOS/DEVICES.js
  WEB/BE/package-lock.json
  WEB/BE/package.json
  WEB/BE/routes/iOS/token/index.js
  WEB/BE/routes/iOS/user/index.js
  WEB/BE/routes/web/user/index.js
  WEB/BE/services/web/auth/index.js
  WEB/BE/utils/crypto/index.js
  WEB/BE/utils/totp/hmac.js
  WEB/BE/utils/totp/index.js
  WEB/FE/src/api/config.ts
  WEB/FE/src/api/index.ts
  WEB/FE/src/components/App.tsx
  WEB/FE/src/components/Footer/Footer.tsx
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/components/LogIn/LogInForm.tsx
  WEB/FE/src/components/MyPage/AccessLog.tsx
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
  WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
  WEB/FE/src/components/StudyComponent/DragAndDrop/Drag.tsx
  WEB/FE/src/components/StudyComponent/DragAndDrop/DropTarget.tsx
  WEB/FE/src/components/StudyComponent/MarkButton/MarkButton.tsx
  WEB/FE/src/components/StudyComponent/StudyBox/StudyBox.tsx
  WEB/FE/src/components/StudyComponent/StudyComponent.tsx
  WEB/FE/src/components/TOTPIntro/TOTPIntroContainer.tsx
  WEB/FE/src/components/Why2FA/Why2FAContainer.tsx
  WEB/FE/src/components/common/Header/Dropdown.tsx
  WEB/FE/src/components/common/Header/Header.tsx
  WEB/FE/src/components/common/Header/Nav.tsx
  WEB/FE/src/components/common/Paragraph.tsx
  WEB/FE/src/components/common/Section/BlockSection.tsx
  WEB/FE/src/layouts/MainPageLayout.tsx
  WEB/FE/src/pages/QRCodePage.tsx
  WEB/FE/src/pages/StudyPage.tsx
  WEB/FE/src/pages/index.tsx
  WEB/FE/src/types/import-file.d.ts
  WEB/FE/src/utils/initialData.ts
  WEB/FE/static/640px-SHAhmac.png
  WEB/FE/static/HMAC.svg
  WEB/FE/static/OTP.svg
  WEB/FE/static/SecretKey.svg
  WEB/FE/static/TOTPFrame.svg
  WEB/FE/static/TimeStamp.svg
  WEB/FE/static/Truncation.svg
  WEB/FE/static/github.svg
  WEB/FE/static/totp-diagram.png
Labels: BE

#340 [iOS] 토큰 서비스 싱크 맞추기 추가
  iOS/DaDaIkSeon/DaDaIkSeon/Common/TOTPTimer.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Model/Token.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/Requestable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenEndpoint.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/ViewModel/BackupPaswordViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/Usecase/MainNetworkResult.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/Usecase/MainUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/CellHandler.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/CheckBoxHandler.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/MainViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenEdit/ViewModel/TokenEditViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/MockTokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenServiceable.swift
Labels: iOS

#346 [iOS] SettingView 네트워크 정리
  iOS/DaDaIkSeon/DaDaIkSeon/Model/Token.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingNetworkResult.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+Email.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+MultiDevice.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
Labels: iOS

#349 [iOS] 백업 서버에서 불러온 데이터 복호화(와 이게 되네요..!)
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/ViewModel/BackupPaswordViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
Labels: iOS

#350 [iOS] Feat/setting network2
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Date+.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
Labels: iOS

#342 [FE,BE] Alert Message 추가 및 타입에러, key warning 해결
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/components/ChangePass/ChangePasswordComponent.tsx
  WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
  WEB/FE/src/components/StudyComponent/StudyBox/StudyBox.tsx
  WEB/FE/src/components/StudyComponent/StudyComponent.tsx
  WEB/FE/src/components/findID/findIDComponent.tsx
  WEB/FE/src/utils/message.ts
Labels: BE, FE

#344 [FE] Axios Response Interceptor 설정
  WEB/FE/src/api/config.ts
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
Labels: FE

#345 [FE,BE] Axios Response Interceptor 설정 변경에 따른 상태 코드 변경
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/middlewares/verifyJWT.js
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/components/LogIn/LogInForm.tsx
Labels: BE, FE

#354 [FE] dist에 favicon 포함
  WEB/FE/config/webpack.common.js
  WEB/FE/src/index.tsx
Labels: FE

#355 [FE] TOTPModal 관련 버그 수정 및 개선
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/components/TOTPModal/OTPInput.tsx
  WEB/FE/src/components/TOTPModal/TOTPModal.tsx
Labels: FE

#357 [BE] 기능구현 2차 배포
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/middlewares/verifyJWT.js
  WEB/FE/config/webpack.common.js
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/api/config.ts
  WEB/FE/src/components/ChangePass/ChangePasswordComponent.tsx
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/components/LogIn/LogInForm.tsx
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
  WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
  WEB/FE/src/components/StudyComponent/StudyBox/StudyBox.tsx
  WEB/FE/src/components/StudyComponent/StudyComponent.tsx
  WEB/FE/src/components/TOTPModal/OTPInput.tsx
  WEB/FE/src/components/TOTPModal/TOTPModal.tsx
  WEB/FE/src/components/findID/findIDComponent.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/utils/message.ts
Labels: BE

#356 [FE] 기능구현 2차 배포
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/middlewares/verifyJWT.js
  WEB/FE/config/webpack.common.js
  WEB/FE/package-lock.json
  WEB/FE/package.json
  WEB/FE/src/api/config.ts
  WEB/FE/src/components/ChangePass/ChangePasswordComponent.tsx
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/components/LogIn/LogInForm.tsx
  WEB/FE/src/components/MyPage/MyPageContainer.tsx
  WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
  WEB/FE/src/components/StudyComponent/StudyBox/StudyBox.tsx
  WEB/FE/src/components/StudyComponent/StudyComponent.tsx
  WEB/FE/src/components/TOTPModal/OTPInput.tsx
  WEB/FE/src/components/TOTPModal/TOTPModal.tsx
  WEB/FE/src/components/findID/findIDComponent.tsx
  WEB/FE/src/index.tsx
  WEB/FE/src/utils/message.ts
Labels: FE

#351 [iOS] Token CRUD
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenEndpoint.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenNetworkManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenServiceable.swift
Labels: iOS

#352 [iOS] 배포 버전 수정
  iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
  iOS/DaDaIkSeon/DaDaIkSeon/Common/BiometricIDAuthManager.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/HeaderView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingUsecase.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView+Views/SettingView+MyInfoSetting.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingViewComponents/SettingViewWrapper.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel.swift
  iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenEdit/ViewModel/TokenEditViewModel.swift
Labels: iOS

#358 [BE] iOS api 수정
  WEB/BE/controllers/iOS/token/index.js
  WEB/BE/services/iOS/token/index.js
Labels: BE

#360 [FE,BE] 에러코드 변경 및 에러코드에 따른 Alert 필터
  WEB/BE/controllers/web/auth/index.js
  WEB/BE/controllers/web/user/index.js
  WEB/BE/middlewares/verifyJWT.js
  WEB/FE/src/api/config.ts
  WEB/FE/src/components/FindPassword/FindPasswordForm.tsx
  WEB/FE/src/components/LogIn/LogInForm.tsx
  WEB/FE/src/components/findID/findIDComponent.tsx
Labels: BE, FE

#361 [FE] useTOTPModal 구현
  WEB/FE/src/api/index.ts
  WEB/FE/src/components/FindPassword/FindPasswordContainer.tsx
  WEB/FE/src/components/LogIn/LogInContainer.tsx
  WEB/FE/src/components/TOTPModal/TOTPModal.tsx
  WEB/FE/src/hooks/useTOTPModal.ts
Labels: FE

#363 [FE] useEmailInput, usePasswordInput, useSignUpInput 구현
  WEB/FE/src/api/index.ts
  WEB/FE/src/components/ChangePass/ChangePasswordComponent.tsx
  WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
  WEB/FE/src/components/findID/findIDComponent.tsx
  WEB/FE/src/hooks/index.ts
  WEB/FE/src/hooks/useEmailInput.ts
  WEB/FE/src/hooks/usePasswordInput.ts
  WEB/FE/src/hooks/useSignUpInput.ts
Labels: FE
